name: Deploy Resume to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Convert Markdown to HTML
      run: |
        mkdir -p dist
        pandoc index.md -s -o dist/index.html --metadata title="Yurie Mori Resume"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
